SkylaskSheep:
   enabled: true
   Spawn Chance:
      - "white:9%"
      - "Silver:6.5%"
      - "yellow:6.5%"
      - "red:6.5%"
      - "brown:6.5%"
      - "gray:6.5%"
      - "green:6.5%"
      - "blue:6.5%"
      - "black:6.5%"
      - "light_blue:6.5%"
      - "pink:6.5%"
      - "cyan:6.5%"
      - "lime:6.5%"
      - "magenta:6.5%"
      - "purple:6.5%"

   Drop dye on death: true
   Death drop chance: "20%"
   Death drop amounts:
      - "1:80%"
      - "2:15%"
      - "3:5%"


   Drop dye on shear: true
   Shear drop chance: "15%"
   Shear drop amounts:
         - "1:80%"
         - "2:15%"
         - "3:5%"